### ISSUE TITLE
Prepare a demo for the midterm presentation

### ISSUE THREAD

**Issue by xordspar0** [xordspar0/Data61-capstone-2016#10]
Our demo should ideally:
1. be able to export routes as KML.
2. style routes based on a predefined rating of "good" or "bad".
3. show mockup tweets in the placemark of some cities (click on the pin on the map to bring up the title, Tweet text, and image URL).
4. get mockup tweet data and route rating from a CSV file that we make.

**Comment by xordspar0** [comment]
3 and 4 might be too ambitious to finish in the next 2 weeks, but I would really like to see them in our demo.

**Comment by xordspar0** [comment]
The demo is dependent on:
- [x] #11 Make a demo CSV file with sample tweets, picture, and their associated cities or coordinates
- [x] #12 Write a function that can import social media data from GeoJSON
- [x] #13 Style data points based on type

**Comment by xordspar0** [comment]
These are all done. We are good to go for the presentation.
