### ISSUE TITLE
Make a demo CSV file with sample tweets, picture, and their associated cities or coordinates

### ISSUE THREAD

**Issue by xordspar0** [xordspar0/Data61-capstone-2016#11]

**Comment by xordspar0** [comment]
Let's do the data directly in GeoJSON, that way we don't have to write a script to convert it.

The demo file should contain 3 "Tweets". Each Tweet should have
1. a lat/lon point
2. the text of the Tweet
3. the user who posted the Tweet

**Comment by xordspar0** [comment]
The demo is dependent on:

- [ ] #11 Make a demo CSV file with sample tweets, picture, and their associated cities or coordinates
- [ ] #12 Write a function that can import social media data from GeoJSON
- [ ] #13 Style data points based on type
